apiVersion: v1
kind: Pod
metadata:
  name: pvc-tester
  namespace: local-path-storage
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Hello > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: test-volume
          mountPath: /data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc