apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: local-path-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path