apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: harbor
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.19.0"

      helm:
        releaseName: harbor
        valueFiles:
          - $values/kubernetes/apps/harbor/values.yaml

    - repoURL: https://github.com/luren9/home-server.git
      targetRevision: main
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true