apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: harbor
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.19.0"

      helm:
        releaseName: harbor
        valueFiles:
          - $values/kubernetes/apps/harbor/values.yaml

    - repoURL: https://github.com/luren9/home-server.git
      targetRevision: main
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
  - group: ""
    kind: Secret
    name: harbor-core
    namespace: harbor
    jsonPointers:
    - /data/secret
    - /data/CSRF_KEY
    - /data/tls.crt
    - /data/tls.key

  - group: ""
    kind: Secret
    name: harbor-jobservice
    namespace: harbor
    jsonPointers:
    - /data/JOBSERVICE_SECRET

  - group: ""
    kind: Secret
    name: harbor-registry
    namespace: harbor
    jsonPointers:
    - /data/REGISTRY_HTTP_SECRET

  - group: ""
    kind: Secret
    name: harbor-registry-htpasswd
    namespace: harbor
    jsonPointers:
    - /data/REGISTRY_HTPASSWD

  - group: apps
    kind: Deployment
    name: harbor-registry
    namespace: harbor
    jsonPointers:
      - /spec/template/metadata/annotations/checksum~1secret
      - /spec/template/metadata/annotations/checksum~1secret-core
      - /spec/template/metadata/annotations/checksum~1secret-jobservice

  - group: apps
    kind: Deployment
    name: harbor-core
    namespace: harbor
    jsonPointers:
      - /spec/template/metadata/annotations/checksum~1secret
      - /spec/template/metadata/annotations/checksum~1secret-jobservice

  - group: apps
    kind: Deployment
    name: harbor-jobservice
    namespace: harbor
    jsonPointers:
      - /spec/template/metadata/annotations/checksum~1secret
      - /spec/template/metadata/annotations/checksum~1secret-core
      - /spec/template/metadata/annotations/checksum~1secret-jobservice
