apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cilium
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: "1.18.2"

      helm:
        releaseName: cilium
        valueFiles:
          - $values/kubernetes/apps/cilium/values.yaml

    - repoURL: https://github.com/luren9/home-server.git
      targetRevision: main
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
