apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tailscale
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale

  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: "1.98.4"

      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/kubernetes/apps/tailscale/values.yaml

    - repoURL: https://github.com/luren9/home-server.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/luren9/home-server.git
      targetRevision: main
      path: kubernetes/apps/tailscale/manifests

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
