helmDefaults:
  diffArgs:
      - "--suppress-secrets"
      - "--suppress-output-line-regex checksum/*"

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: harbor
    url: https://helm.goharbor.io
  - name: cilium
    url: https://helm.cilium.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts



releases:

  - name: metallb-config
    namespace: metallb-system
    chart: ./metallb/metallb-config

  - name: velero
    namespace: velero
    chart: vmware-tanzu/velero
    version: 11.2.0
    values:
      - ./velero/values.yaml
    set:
      - name: upgradeCRDs
        value: "true"
